### ISSUE TITLE
[Request] Chaos;Head Noah on Steam

### ISSUE THREAD

**Issue by Naso137** [0xDC00/scripts#107]
https://vndb.org/v22505 or  https://vndb.org/r93152

**Comment by Blu3train** [comment]
+1

**Comment by DanilaSidukov** [comment]
> https://vndb.org/v22505 or  https://vndb.org/r93152

Bro, do you know about Committee of Zero? They almost done normal translation to English with patch contains non-censored version from XBox

**Comment by Blu3train** [comment]
But I want to translate it into my native language.

**Comment by animator2048** [comment]
+1

**Comment by ExonorGit** [comment]
+1

**Comment by KillJuiceLmao** [comment]
+1

**Comment by 2DTengu** [comment]
+1

**Comment by WilsonNet** [comment]
+1
