### ISSUE TITLE
[Request] "Memories Off -Innocent Fille-" and "Memories Off -Innocent Fille- for Dearest" (PC) by MAGES.

### ISSUE THREAD

**Issue by JRaptor22** [0xDC00/scripts#108]
Good afternoon DC.

My name's JRaptor22. I would like your help with these 2 games: "Memories Off -Innocent Fille-" and "Memories Off -Innocent Fille- for Dearest" (PC / The PC Version).

I tried to hook it with Textractor but I can't get the texts out from these games at all. Please help me with your amazing scripts so I can hook the texts of these games to be translated with MTL tools.

Below are the VNDB links for this game:

Memories Off -Innocent Fille- : https://vndb.org/v21964
Memories Off -Innocent Fille- for Dearest : https://vndb.org/v23725

Thank you for your attention.

Best regards,

JRaptor22

**Comment by JRaptor22** [comment]
For Memories Off -Innocent Fille- for Dearest, the game I downloaded is in Chinese (not Japanese) so probably this is the cause of some weird things. 

I tried to use the PC_Steam_MAGES_Chaos;Child.js and it kinda worked but some words will display some random codes like ox98a or something like that. There are some instances where the word will be displayed as a box alongside other words.

**Comment by koukdw** [comment]
Well you need the charset. If you look at all the scripts using the mages engine it's included. Now the problem, i have no idea where to find it for that game it probably need to be generated.

From what i gathered in the Committee of Zero discord, they extract the font texture from system.cpk you can use garbro for this and run it through some ocr software and fix the ocr mistakes. Then you modify the chaos-child script to use your next charset.

**Comment by JRaptor22** [comment]
Morning koukdw.

I'm sorry, but I didn't know how to do those things where I can just extract the words from system.mpk and use programs like garbro, ocr, and stuff like that.
I only tried to test all MAGES scripts in the library to see whether or not they can successfully hook the texts from these games.
I still got hooking problem with Memories Off -Innocent Fille- for Dearest. I can't find any script that works with this game.

Thank you.

**Comment by 0xDC00** [comment]
JP+EN only, no plans for ZHC.

![image](https://user-images.githubusercontent.com/29352751/217534781-bdd82f62-defe-45d3-b44a-248b5d142aa1.png)
