### ISSUE TITLE
[Request] Spade no Kuni no Alice ~Wonderful White World~

### ISSUE THREAD

**Issue by Csien** [0xDC00/scripts#12]
Looking for the script of Spade no Kuni no Alice ～Wonderful White World～ | スペードの国のアリス ～Wonderful White World～

**Comment by DesireSai** [comment]
+1 Request!

**Comment by Hidarin** [comment]
+1 Request!

**Comment by tsukina22** [comment]
+1 Request

**Comment by eva-likes-stuff** [comment]
+1 It's a shame that Quinrose went bankrupt, but at least we have this game for the Switch from Otomate!
