### ISSUE TITLE
(REQUEST) MAHOUTSUKAI NO YORU NINTENDO SWITCH 

### ISSUE THREAD

**Issue by Mcrmitz** [0xDC00/scripts#120]
Since mahoyo switch will be released in a few days, is it possible to create a script for mahoyo?

My English is not very good and I will be using deepl in my language. Please make it and thank you for your hard work Agent.

**Comment by kanjieater** [comment]
In @0xDC00 we trust! LET'S GOOOOOOO!!!!

**Comment by kanjieater** [comment]
FYI it does hook with textractor, but the hook changes each time you start Yuzu. https://twitter.com/kanjieater/status/1600993365545299968

It's a decent work around until we are blessed with an Agent script

**Comment by Mcrmitz** [comment]
> FYI it does hook with textractor, but the hook changes each time you start Yuzu. https://twitter.com/kanjieater/status/1600993365545299968
> 
> It's a decent work around until we are blessed with an Agent script

We expect agent to create script for mahoyo switch

**Comment by koukdw** [comment]
Done check the pull requests if you want the script
