### ISSUE TITLE
[Request] BROTHERS CONFLICT Precious Baby

### ISSUE THREAD

**Issue by fon276** [0xDC00/scripts#13]
I'm looking for the script of Brothers Conflict: Precious Baby ブラザーズ コンフリクト, BroCon, ブラコン for Nintendo Switch. If you can share it, i would be grateful

**Comment by DesireSai** [comment]
+1 Request! But idk if it's just me but it doesn't run on Yuzu for me, it only works on Ryujinx D:

**Comment by iiuuoow** [comment]
+1 Request. This game is now available for both Yuzu and Ryujinx. would be very grateful make a script!

**Comment by Hiiyo** [comment]
+1 Request!

**Comment by koukdw** [comment]
thanks @Hiiyo https://github.com/0xDC00/scripts/pull/290/files
