### ISSUE TITLE
[Request] Kenka Banchou Otome

### ISSUE THREAD

**Issue by amy10111111111** [0xDC00/scripts#137]
https://vndb.org/v17750
I didnt see except for one game a script on PSVITA emulator but I hope this one gets a script

**Comment by rururu-ruru** [comment]
very much please +1

**Comment by iiuuoow** [comment]
+1 request. really want!

**Comment by namseokgay** [comment]
+1 please!!

**Comment by eva-likes-stuff** [comment]
+1 This one would be awesome! :D
