### ISSUE TITLE
[Request] Jack Jeanne

### ISSUE THREAD

**Issue by peticho** [0xDC00/scripts#14]
If someone could share the script for Jack Jeanne | ジャックジャンヌ I'd really appreciate it!

**Comment by DesireSai** [comment]
+1 Request!

**Comment by Quizzle01** [comment]
+1 Request!

**Comment by monbrei** [comment]
+1 Request!

**Comment by iiuuoow** [comment]
I made a script for this. It must set the game version to 1.0.5. and play Yuzu. 
[NS_01001DD010A2E000_Jack_Jeanne.zip](https://github.com/0xDC00/scripts/files/13696318/NS_01001DD010A2E000_Jack_Jeanne.zip)
Unzip it and put the script in \agent-v0.1.3-win32-x64\data\scripts and run agent. Have fun!

**Comment by Bluebird2323** [comment]
> I made a script for this. It must set the game version to 1.0.5. and play Yuzu. [NS_01001DD010A2E000_Jack_Jeanne.zip](https://github.com/0xDC00/scripts/files/13696318/NS_01001DD010A2E000_Jack_Jeanne.zip) Unzip it and put the script in \agent-v0.1.3-win32-x64\data\scripts and run agent. Have fun!


You are a genius, thanks!
