### ISSUE TITLE
[REQUEST] Reine des Fleurs (Switch)

### ISSUE THREAD

**Issue by michibikun** [0xDC00/scripts#143]
https://vndb.org/v14919

I would like to request for the script of Reine des fleurs Switch version. Thank you so much!

**Comment by DoggieCat** [comment]
+1

**Comment by Bluebird2323** [comment]
I did this script already, but forgot to do a pull request, I'll do that now!

**Comment by DoggieCat** [comment]
Thank you so much! <3
