### ISSUE TITLE
[Request] DRAGON QUEST® XI S: Echoes of an Elusive Age™ - Definitive Edition Jデポ (Steam) Unreal Engine

### ISSUE THREAD

**Issue by lordfarnam** [0xDC00/scripts#147]
Looking for this version: https://steamdb.info/depot/1295512/

This has japanese voice acting and furigana over the text. I think it's japan only release. It looks like this can only be activated in japan but i can help with getting info if need be.

**Comment by UMNV** [comment]
There is a mod for the western version that changes the text to japanese, idk if it's possible but if at least they could hook the text from the mod would be also great for those who can't get the japanese version.

the mod:
https://www.nexusmods.com/dragonquestxisdefinitiveedition/mods/78?tab=description
