### ISSUE TITLE
[Request] Higurashi When They Cry

### ISSUE THREAD

**Issue by Issue-maker-9000** [0xDC00/scripts#191]
This game has multiple chapters first chapter is available for free on steam and gog
https://store.steampowered.com/app/310360/Higurashi_When_They_Cry_Hou__Ch1_Onikakushi/
https://www.gog.com/en/game/higurashi_when_they_cry_hou_ch1_onikakushi

**Comment by ukw16** [comment]
Also asking. Can supply the game's actual scripts for Ch.1 and 2 if required.
