### ISSUE TITLE
[Request] 9 R.I.P.

### ISSUE THREAD

**Issue by HopePenarubia** [0xDC00/scripts#193]
Exactly as the title says. If possible, a script that's compatible with Ryujinx too, please.

https://vndb.org/v38068
https://store-jp.nintendo.com/list/software/70010000064389.html

**Comment by 1ightheart** [comment]
+1 Request ! It would be great, be it Yuzu or Ryujinx!

**Comment by xMaryZx** [comment]
+1

**Comment by Quizzle01** [comment]
+ 1 request please!

**Comment by Hidarin** [comment]
+1

**Comment by MelonCakey** [comment]
+1 - would love this as well!

**Comment by koukdw** [comment]
Done https://github.com/0xDC00/scripts/commit/0f77d9ef75da5f884a2a448a5ae58d385efc96e9
Please report any problem on discord, there's some part of the script that is hard to test without playing the full game.
A save just before the problem would be useful too.

**Comment by HopePenarubia** [comment]
> Done [0f77d9e](https://github.com/0xDC00/scripts/commit/0f77d9ef75da5f884a2a448a5ae58d385efc96e9) Please report any problem on discord, there's some part of the script that is hard to test without playing the full game. A save just before the problem would be useful too.

Yeyyy!!! Thank you very much!!!!
