### ISSUE TITLE
[Request] Tokimeki Memorial Girl's Side: 4th Heart

### ISSUE THREAD

**Issue by hanakou** [0xDC00/scripts#2]
Game: Tokimeki Memorial Girl's Side: 4th Heart / ときめきメモリアル Girl's Side 4th Heart

**Comment by DesireSai** [comment]
+1 Request! 🥰

**Comment by 0xDC00** [comment]
Demo: https://youtu.be/yvajP5Wtp6U
Please share it to others, reddit,....

Use script updater to get the latest version of scripts.
<https://www.youtube.com/watch?v=c0aVSr_nYJ0&list=PLTZXVVG9AT6Sbl1Yg42sxzVAS6IMfnaNH&index=1>

**Comment by HyemiChan** [comment]
Hello, i tested this script, and it wont work anymore since the game updated to 1.0.1.. this script works only on 1.0.0 version. I hope you will the update the script according to the update if possible.. thanks a lot :)

**Comment by 0xDC00** [comment]
@HyemiChan Hi,
Most script focused on base version (1.0.0),
(I have no plan to support every update for each game; its too many)
Just remove the update.

**Comment by HyemiChan** [comment]
@0xDC00 aww, I see 😭😭.. its ok.. anyway, thank you for providing this script😃😃😃
