### ISSUE TITLE
[REQUEST] Wand of Fortune R (Nintendo Switch)

### ISSUE THREAD

**Issue by KROBecerraL** [0xDC00/scripts#206]

**Comment by iiuuoow** [comment]
Want!

**Comment by eva-likes-stuff** [comment]
+1 Yes, this series seems so fun! 😍

**Comment by iiuuoow** [comment]
Script for Wand of Fortune R. Enjoy!
[NS_01000C7019E1C000_Wand_of_Fortune_Ｒ_for_Nintendo_Switch.zip](https://github.com/0xDC00/scripts/files/13821119/NS_01000C7019E1C000_Wand_of_Fortune_._for_Nintendo_Switch.zip)

**Comment by eva-likes-stuff** [comment]
> Script for Wand of Fortune R. Enjoy! [NS_01000C7019E1C000_Wand_of_Fortune_Ｒ_for_Nintendo_Switch.zip](https://github.com/0xDC00/scripts/files/13821119/NS_01000C7019E1C000_Wand_of_Fortune_._for_Nintendo_Switch.zip)

Thank you! 😍

**Comment by eva-likes-stuff** [comment]
I think this should be closed since the script's already been made

**Comment by koukdw** [comment]
thank you
