### ISSUE TITLE
[Request] Dies irae ～Amantes amentes～ HD

### ISSUE THREAD

**Issue by CrAZONE0** [0xDC00/scripts#215]
The HD version of Dies irae ～Amantes amentes～

**Comment by koukdw** [comment]
It's already there

**Comment by CrAZONE0** [comment]
> It's already there

Acta est Fabula is, Amantes amentes is not.

**Comment by koukdw** [comment]
It's the same game without the Hentai scenes. The script support both.

**Comment by CrAZONE0** [comment]
> The script support both.

You're correct. I'll say it's a bit ambiguous though, renaming the script to Dies Irae HD -Animation anniversary- o maybe add another one for Amantes amentes would be clearer. Thanks.
