### ISSUE TITLE
[REQUEST] [PSVITA] Moshi, Kono Sekai ni Kami-sama ga Iru to Suru Naraba

### ISSUE THREAD

**Issue by chisani** [0xDC00/scripts#219]
I'd like to request a script for Moshi, Kono Sekai ni Kami-sama ga Iru to Suru Naraba game. Thank you in advance!

**Comment by desideratacym** [comment]
+ request please!

**Comment by Otomekun06** [comment]
+1!

**Comment by chisani** [comment]
I'm trying to do it myself but it's so hard :( Can't use CE...I've tried everything!

**Comment by Hidarin** [comment]
+1

**Comment by amy10111111111** [comment]
> I'm trying to do it myself but it's so hard :( Can't use CE...I've tried everything!
 
It wont work with CE because the engine is unity which means it uses a method to store the text

**Comment by chisani** [comment]
> > I'm trying to do it myself but it's so hard :( Can't use CE...I've tried everything!
> 
> It wont work with CE because the engine is unity which means it uses a method to store the text

Oh so this why. So in the end it is impossible to hook and make a script for this game in the end :(

**Comment by koukdw** [comment]
Join the discord script related discussion mostly happen there
