### ISSUE TITLE
[REQUEST] Phoenix Wright: Ace Attorney Trilogy (PC)

### ISSUE THREAD

**Issue by CrAZONE0** [0xDC00/scripts#228]

**Comment by 2DTengu** [comment]
+

**Comment by aquiab** [comment]
hey!, i made a script for it https://github.com/0xDC00/scripts/blob/2c4daa52cfc29d7e9c536ad5d262ef37943ac4df/PC_Steam_Unity_Phoenix_Wright_Ace_Attorney_Trilogy.js
its my first one so if i see any errors or missing things while im playing through the games, ill try fixing it
