### ISSUE TITLE
[Request] Umineko no Naku Koro ni Saku ~Nekobako to Musou no Koukyoukyoku~ (Switch)

### ISSUE THREAD

**Issue by kanjieater** [0xDC00/scripts#25]
This version includes new voiced arcs, lip sync, sprite/background/rain animations, song subtitles, line jump within the backlog, and several others improvements. (Higurashi's switch port is also a fantastic improvement.)

**Comment by torihiki123** [comment]
+1

**Comment by damiansh** [comment]
+1
