### ISSUE TITLE
[Request] The Fortune Princess of Temirana and the Knights of Misfortune (Nintendo Switch)

### ISSUE THREAD

**Issue by jenyjj** [0xDC00/scripts#255]

**Comment by MelonCakey** [comment]
+1 to this! 
![67804_jpg](https://github.com/0xDC00/scripts/assets/83950315/ddd57420-449e-4ee9-aa95-0ac96b2356a8)

**Comment by iiuuoow** [comment]
I made a script for this. Everything works fine except Choice sentence. I hope it helps :)
(This only works with Ryujinx.)
[Temirana_Ryujinx.zip](https://github.com/0xDC00/scripts/files/13692647/Temirana_Ryujinx.zip)
Unzip it and put the script in \agent-v0.1.3-win32-x64\data\scripts and run agent.

**Comment by MelonCakey** [comment]
![Temirana script ingame](https://github.com/0xDC00/scripts/assets/83950315/6f9a91c3-5730-43b5-8067-1eaed67a77f5)


> I made a script for this. Everything works fine except Choice sentence. I hope it helps :) (This only works with Ryujinx.) [Temirana_Ryujinx.zip](https://github.com/0xDC00/scripts/files/13692647/Temirana_Ryujinx.zip) Unzip it and put the script in \agent-v0.1.3-win32-x64\data\scripts and run agent.

Just gave it a quick run and wanted to say thank you so much! Works wonderfully, even in the Options menu's. Excited to really start this after I get through my backlog, and Ryujinx has always been my preference so even better!
