### ISSUE TITLE
[Request] キューピット・パラサイト  Cupid Parasite (Nintendo Switch)

### ISSUE THREAD

**Issue by aryamira** [0xDC00/scripts#298]
I saw that there is one for the fandisk but this would be amazing as well!

**Comment by eva-likes-stuff** [comment]
I'm pretty sure there is one for the main games as well

**Comment by koukdw** [comment]
https://github.com/0xDC00/scripts/blob/main/NS_0100F7E00DFC8000_Cupid_Parasite

There is.

**Comment by aryamira** [comment]
This one doesn't show up in agent for soem reason, am I doing something wrong?

**Comment by koukdw** [comment]
Update your scripts and refresh

**Comment by aryamira** [comment]
didn't work
https://youtu.be/8013yza_drE

**Comment by koukdw** [comment]
I fixed it try again

**Comment by aryamira** [comment]
worked now, you are awesome thanks c:
