### ISSUE TITLE
[Request] Persona 3 Reload

### ISSUE THREAD

**Issue by Mosencrantz** [0xDC00/scripts#313]
https://store.steampowered.com/app/2161700/Persona_3_Reload/

**Comment by Jambo-Wambo** [comment]
Would also like +

**Comment by SaberActive** [comment]
Same please 🙏

**Comment by zeturin44** [comment]
Doesn't seem to work for me on a gamepass version... Could be an issue with the big dlc, but not sure about that

**Comment by koukdw** [comment]
> Doesn't seem to work for me on a gamepass version... Could be an issue with the big dlc, but not sure about that

Game updated pattern broke, i don't have access to the game anymore (i dont have gamepass anymore)

**Comment by zeturin44** [comment]
> > Doesn't seem to work for me on a gamepass version... Could be an issue with the big dlc, but not sure about that
> 
> Game updated pattern broke, i don't have access to the game anymore (i dont have gamepass anymore)

I could provide you with a gamepass account if you would be ready to update the script, I just got myself a gamepass to play that game in jap...

**Comment by koukdw** [comment]
I'm busy with other projects rn sorry

**Comment by zeturin44** [comment]
Ok it's fine! Thanks for amazing work!
