### ISSUE TITLE
[Request] Like a Dragon: Infinite Wealth (PC)

### ISSUE THREAD

**Issue by Jambo-Wambo** [0xDC00/scripts#315]
https://store.steampowered.com/app/2072450/Like_a_Dragon_Infinite_Wealth/

**Comment by Kalleo1** [comment]
It's on Agent's discord server https://discord.com/channels/867944111557201980/867944111557201983/1201783647318048819

**Comment by 4804032140** [comment]
Shouldn't this be added to the repo?

**Comment by Kalleo1** [comment]
It seems the script doesn't get the text from some cutscenes where you can't press to continue the dialogs, so I would guess that's why it's not on the repo yet
