### ISSUE TITLE
[Request] Memories Off Historia (Steam)

### ISSUE THREAD

**Issue by UnbrokenStreetlight** [0xDC00/scripts#322]
Seems like some of the games have been figured out on Switch and other consoles, so having the PC versions would be really helpful to play the most accessible versions of the games.

**Comment by koukdw** [comment]
Check the pull requests, someone made a scripts for those games. The reason we don't accept it is that we want to fix libmages instead of applying bandaid. We don't have access to the game. So we are waiting for someone to provide it to us the game binary.

**Comment by 4804032140** [comment]
I'm the one who wrote the PR https://github.com/0xDC00/scripts/pull/310. It's named after seven but it should work for all of them. The only games I've done no testing on are 5 and 6. Sorekara seems to have an issue when text appears in mail form. A bunch of extra dialog and escape sequences or something get dumped, but that's the only bug I've found so far. If you find any more then lmk. I'll try to get this merged properly soon.
