### ISSUE TITLE
[Request] Temirana Koku no Tsuiteru Hime to Tsuitenai Kishi Dan (Switch)

### ISSUE THREAD

**Issue by amadeowolfgang** [0xDC00/scripts#382]
Title: Temirana Koku no Tsuiteru Hime to Tsuitenai Kishi Dan
English Title: The Fortune Princess of Temirana and the Knights of Misfortune
JP Title: テミラーナ国の強運姫と悲運騎士団
Platform: Nintendo Switch

https://vndb.org/v34020

A script for this game, please? Thank you so much.

**Comment by amy10111111111** [comment]
Done 08016949a4f00aadc2ec4e1564253d0a4bc4c302

**Comment by amy10111111111** [comment]
Done 08016949a4f00aadc2ec4e1564253d0a4bc4c302
