### ISSUE TITLE
[Request] BUSTAFELLOWS Season 2 (ANDROID) or Switch

### ISSUE THREAD

**Issue by HyemiChan** [0xDC00/scripts#383]
Would like to request for this .. if possible, on android ver. but its also ok on switch ver. Thank you so much :)

**Comment by koukdw** [comment]
It's already made. https://github.com/0xDC00/scripts/blob/main/NS_0100874017BE2000_Unity_BUSTAFELLOWS_season2.js

**Comment by HyemiChan** [comment]
Thank you so much:)
