### ISSUE TITLE
[REQUEST] NS SWITCH : HIIRO NO KAKERA Tamayori Hime Kitan

### ISSUE THREAD

**Issue by chisani** [0xDC00/scripts#522]
https://vndb.org/r119577

**Comment by kanjieater** [comment]
I think this would probably be the same engine as https://github.com/0xDC00/scripts/issues/361

So maybe another one @Kalleo1 could figure out  (when they are back from their break) 🙇‍♂️🙇‍♂️🙇‍♂️

**Comment by amy10111111111** [comment]
Done [829880a](https://github.com/0xDC00/scripts/commit/829880afd778dde2b1463103d5aedd0b1ea35819)
