### ISSUE TITLE
[Request] My Next Life as a Villainess: All Routes Lead to Doom!: Pirates that Stir the Waters (Nintendo Switch)

### ISSUE THREAD

**Issue by DBS30** [0xDC00/scripts#53]

**Comment by tsukina22** [comment]
+1 Request

**Comment by DesireSai** [comment]
There's already [a script for this game](https://github.com/0xDC00/scripts/blob/main/NS_0100982015606000_HamefuraPirates.js).

**Comment by tsukina22** [comment]
Can somebody tell me which version of Yuzu i should use? Any version works or there is a specific one?

**Comment by DesireSai** [comment]
> Can somebody tell me which version of Yuzu i should use? Any version works or there is a specific one?

Try the 996 version~
