### ISSUE TITLE
[bug] NS Switch scripts error

### ISSUE THREAD

**Issue by sakurakocho** [0xDC00/scripts#530]
These scripts show error for Agent 0.1.4 and yuzu 1734
https://github.com/0xDC00/scripts/blob/735b7a42e251e7e4f14f22c765ac367b3fa7a6a0/NS_01006A300BA2C000_Umineko_no_Naku_Koro_ni_Saku.js
https://github.com/0xDC00/scripts/blob/735b7a42e251e7e4f14f22c765ac367b3fa7a6a0/NS_01001DC01486A000_Tsukihime.js
Game version is 1.0.0 for Umineko and 1.0.2 for Tsukihime
Umineko got ReferenceError: katakanaMap is not initialized
Tsukihime got ReferenceError: decoder is not initialized

**Comment by koukdw** [comment]
I can't reproduce your problem.
Update your scripts and make sure to hook before launching the game.

**Comment by koukdw** [comment]
Mhh someone on the discord had the same problem a few month ago.
You need to update agent (the program not the scripts)
