### ISSUE TITLE
[Request] Kin'iro no Corda 2f 金色のコルダ2 f コーエーテクモ the Best script (PSP)

### ISSUE THREAD

**Issue by yanchan00** [0xDC00/scripts#54]
I would really appreciate it if you could also find scripts for Corda 1 and Corda 3 PSP versions, PPSSPP preferably (´• ω •`) ♡  

1. Corda 1 (VNR can hook the game text only, but not the interactive part with the love interests, which is half-game)
2. Corda 2 and Corda 3 don't hook at all, cheat engine can't find anything. VNR doesn't hook at all too. PSP agent scripts don't work too. 
Thank you in advance!

**Comment by DesireSai** [comment]
+1

**Comment by lescats** [comment]
+1 request

**Comment by 0xDC00** [comment]
@yanchan00 PSP agent scripts?

Done,
![image](https://user-images.githubusercontent.com/29352751/180633739-593b6fde-afde-4875-821c-fdb63db798c1.png)
