### ISSUE TITLE
[Request] NS Switch: Hayarigami 1-2-3 Pack

### ISSUE THREAD

**Issue by favidelta** [0xDC00/scripts#597]
https://vndb.org/r106354

**Comment by amy10111111111** [comment]
I already opened an  Issue for this one a year ago https://github.com/0xDC00/scripts/issues/210

I tried to find a hook using the tracer script.Unfortunately ,it seems to have the same issue with the shin Hayarigami series where it loads the code at runtime which means we cant find a good hook without advanced tools like ida pro
