### ISSUE TITLE
[Request] Toraware no Paruma Refrain 囚われのパルマ Refrain

### ISSUE THREAD

**Issue by Fumisu** [0xDC00/scripts#6]
Thank you very much for making a script for Toraware no Palm but could you make a script for Toraware no Paruma Refrain 囚われのパルマ Refrain too (ID: 01000EA00D2EE000) applied for Ryujinx? It's a sequel.

**Comment by DesireSai** [comment]
+1 Request! ^^

**Comment by 0xDC00** [comment]
Unfortunately, there are no plans for Ryujinx support.
Yuzu only.
