### ISSUE TITLE
[Request ] Jewelry Hearts Academia We Will Wing Wonder World (Switch)

### ISSUE THREAD

**Issue by amy10111111111** [0xDC00/scripts#655]
https://vndb.org/v33175
The game doesnt run on yuzu so I couldnt make a script using script tracer . however ,it works on Ryujinx just fine 
The encode of the text is UTF8 .

**Comment by koukdw** [comment]
Use sudachi

**Comment by amy10111111111** [comment]
> Use sudachi it works (it also use NeXAS engine if you plan to make a script)

Which version ?

**Comment by koukdw** [comment]
Just use the latest, the latest tracer i posted with UI should work

**Comment by koukdw** [comment]
0x805DEB10

use this address

**Comment by amy10111111111** [comment]
> 0x805DEB10

wow that was fast thanks, I will edit the script .

**Comment by koukdw** [comment]
Come in the discord

**Comment by amy10111111111** [comment]
Done
