### ISSUE TITLE
[Request] Sweet Clown ~Gozen San-ji no Okashi na Doukeshi~

### ISSUE THREAD

**Issue by Zereste** [0xDC00/scripts#7]
I'd really appreciate it if someone could find and share the script for this otome game (Switch version): Sweet Clown -Gozen San-ji no Okashi na Doukeshi- / Sweet Clown -午前三時のオカシな道化師-

Thanks in advance!

**Comment by DesireSai** [comment]
+1 Request!

**Comment by Quizzle01** [comment]
+1 Request!

**Comment by desideratacym** [comment]
+request please!

**Comment by Otomekun06** [comment]
+1 REQUEST
