### ISSUE TITLE
[Request] Tengoku Struggle -strayside- (Nintendo Switch) # I tried it a little bit!

### ISSUE THREAD

**Issue by mobrei** [0xDC00/scripts#83]
I hope this will help you find the script.

I tried to find the text of the "Tengoku Struggle" game with Cheat Engine and Agent. I found the address in UTF-16, UTF-32. However, the address of UTF-16 shows proper text, but does not move when the game is running. UTF-32's address worked with the game, so I guess UTF-32 would be more accurate.

This game is very interesting. Please upload the script of this game quickly. Thank you.

**Comment by DesireSai** [comment]
+1 Request!

**Comment by haruny8** [comment]
+1 Request please!
