### ISSUE TITLE
[Request] Uta no Prince-sama Repeat

### ISSUE THREAD

**Issue by cecilantro** [0xDC00/scripts#9]
I'd be really thankful if someone could get the script of uta no prince-sama repeat and share it! thank you very much ☺☺

**Comment by DesireSai** [comment]
+1 Request~

**Comment by duskcrow359** [comment]
+1

**Comment by eva-likes-stuff** [comment]
+1 Uta no Prince-sama seems like such a fun, colorful game! 😄
